# Spring boot
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    # MVCC=TRUE
    # - H2 DB? ?? ?? ???? ???? ???? ?
    # - H2 1.4 ???? MVCC ??? ???? ???? ??? ??? ??? ??.
    #    url: jdbc:h2:tcp://localhost/~/springbootjpa;MVCC=TRUE
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    #driver-class-name: org.h2.Driver
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          #          show_sql: true
          format_sql: true
logging:
  level:
    org-hibernate.SQL : debug
    org.hibernate.type : trace
