spring:
  servlet:
    multipart:
      #location: '/var/ez2db/repository/'
      location: 'C:\\ez2db\\repository\\'
      max-file-size: 25MB
      max-request-size: 50MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true
          format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
logging:
  level:
    org-hibernate.SQL : info
    org.hibernate.type : trace

server:
  servlet:
    encoding:
      charset: utf-8
      force: true