# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      with:
        host: ${{ secrets.host }}
        port: ${{ secrets.port }}
        username: ${{ secrets.username }}
        key: ${{ secrets.sshkey }}
        java-version: "11.x"
        script: |
          cd ${{ secrets.path }}
          git pull https://${{ secrets.githubRepoToken }}@github.com/{orgname}/{repo}.git master
          java -jar ./build/EZ2DB-0.0.1-SNAPSHOT.jar
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
